namespace PhyrosClassroom.Academics.Models;

public sealed record AcademicReadModel(
    Guid AcademicId,
    string AcademicCode,
    string GivenName,
    string FamilyName,
    DateTimeOffset RegisteredAtUtc,
    string? SourceSystem,
    string? SourceReference,
    DateOnly? BirthDate,
    string? GradeLevel,
    string? PrimaryGuardianName,
    string? PrimaryGuardianEmail,
    bool HasMedicalAlert,
    string? MedicalNotes,
    bool HasIep,
    IReadOnlyList<AcademicDocumentReference> Documents,
    IReadOnlyList<AcademicRecordNote> Notes,
    string SubjectId = "",
    Guid? SourceRegistrationId = null,
    string? SourceRegistrationStatus = null,
    DateTimeOffset? SourceRegistrationUpdatedAtUtc = null,
    string AcademicName = "",
    bool WantsEmailNotifications = false,
    bool WantsSmsNotifications = false,
    string? OnboardingStatus = null,
    IReadOnlyList<AcademicContact>? Contacts = null,
    IReadOnlyList<AcademicStudent>? Students = null,
    DateTimeOffset? UpdatedAtUtc = null);
