namespace PhyrosClassroom.Academics.Models;

public sealed record AcademicEventRecord(
    Guid AcademicId,
    string EventType,
    DateTimeOffset OccurredUtc,
    string AcademicCode,
    string GivenName,
    string FamilyName,
    string? SourceSystem = null,
    string? SourceReference = null,
    DateOnly? BirthDate = null,
    string? GradeLevel = null,
    string? PrimaryGuardianName = null,
    string? PrimaryGuardianEmail = null,
    bool HasMedicalAlert = false,
    string? MedicalNotes = null,
    bool HasIep = false,
    IReadOnlyList<AcademicDocumentReference>? Documents = null,
    IReadOnlyList<AcademicRecordNote>? Notes = null,
    string SubjectId = "",
    Guid? SourceRegistrationId = null,
    string? SourceRegistrationStatus = null,
    DateTimeOffset? SourceRegistrationUpdatedAtUtc = null,
    string AcademicName = "",
    bool WantsEmailNotifications = false,
    bool WantsSmsNotifications = false,
    string? OnboardingStatus = null,
    IReadOnlyList<AcademicContact>? Contacts = null,
    IReadOnlyList<AcademicStudent>? Students = null);
